server:
  port: 8080
  
spring:
  application:
    name: tmdl-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      # ddl-auto: create-drop
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

okta:
  oauth2:
    issuer: https://${AUTH0_DOMAIN}/
    audience: ${SPRING_BOOT_URL}
    groupsClaim: permissions